# Generated by Django 4.2.7 on 2026-06-01 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ['-month']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterField(
            model_name='budget',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='finance.category'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.DateField(help_text='Первый день месяца'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('food', '🍔 Еда'), ('transport', ' Транспорт'), ('entertainment', '🎬 Развлечения'), ('utilities', '💡 Коммуналка'), ('health', '🏥 Здоровье'), ('education', '📚 Образование'), ('salary', '💰 Зарплата'), ('freelance', '💻 Фриланс'), ('investments', '📈 Инвестиции'), ('other', ' Другое')], db_index=True, max_length=50),
        ),
    ]
