# Generated by Django 4.2.7 on 2026-06-03 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0003_financialgoal_alter_budget_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialGoalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='finance.financialgoal')),
            ],
            options={
                'verbose_name': 'История цели',
                'verbose_name_plural': 'Истории целей',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('account_type', models.CharField(choices=[('bank', '🏦 Банковский счёт'), ('card', '💳 Карта'), ('broker', '📈 Брокерский счёт'), ('cash', '💵 Наличные'), ('deposit', '🏛️ Вклад'), ('other', ' Другое')], max_length=20, verbose_name='Тип счёта')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Текущий баланс')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-account_type', 'name'],
            },
        ),
    ]
