# Generated by Django 4.2.7 on 2026-06-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_financialgoalhistory_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, help_text='Уникальный идентификатор из банка (код авторизации)', max_length=100, null=True, unique=True, verbose_name='Внешний ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('bank', '🏦 Банковский счёт'), ('card', '💳 Карта'), ('broker', '📈 Брокерский счёт'), ('cash', '💵 Наличные'), ('deposit', '🏛️ Вклад'), ('other', '📋 Другое')], max_length=20, verbose_name='Тип счёта'),
        ),
    ]
